sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build master branch only
script:
  - npm install hexo-generator-search --save # 安装本地搜索插件
  - npm install hexo-renderer-jade --save
  - npm install hexo-renderer-stylus --save
  - npm audit fix -f # 执行修复命令
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
  local-dir: public
  target_branch: master
